In [1]:
import torch

## Defining Sigmoid Activation Function

In [3]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

## Generating Dummy Data

In [7]:
torch.manual_seed(7)
features = torch.randn(1,5)
weight = torch.randn_like(features)
bias = torch.randn(1,1)

In [8]:
print(features.shape)
print(weight.shape)
print(bias.shape)

torch.Size([1, 5])
torch.Size([1, 5])
torch.Size([1, 1])


## Lets Calculate the Output of Simple NN

In [9]:
output = torch.sum(weight*features,bias)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input)
 * (Tensor input, torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor)
 * (Tensor input, tuple of ints dim, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, Tensor out)


Matrix Multiplication cannot be performed on above matrices beacause they doesnt satisfy the property.so lets reshape the 'weight' vector

In [11]:
a = weight.reshape((5,1))
b = weight.view((5,1))
c= weight.resize_(5,1)

In [13]:
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([5, 1])
torch.Size([5, 1])
torch.Size([5, 1])


### Differences between the shaping techniques

reshape method returns a new tnesor and does the reshaping by copying the data to another part of menory
view method will return new tensor with same data as weights and size
resize will return same tensor with different shape but it has to loose certain elements from tensor not from memory)


###### Prefered : weight.view

In [15]:
output = (torch.mm(b,features))+bias

In [16]:
output

tensor([[ 0.4490, -0.3858, -0.5296,  1.3148, -1.1953],
        [ 0.3699,  0.0381, -0.0190,  0.7140, -0.2836],
        [ 0.1368,  1.2865,  1.4845, -1.0556,  2.4014],
        [ 0.2974,  0.4263,  0.4485,  0.1637,  0.5513],
        [ 0.5646, -1.0048, -1.2751,  2.1922, -2.5266]])

## Lets Model a Simple Neural Network 

### Input Layer 
### Hidden Layer(s)
### Output Layer

In [21]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

print(W1.shape)
print(W2.shape)
print(B1.shape)
print(B2.shape)
print('Features Shape',features.shape)

torch.Size([3, 2])
torch.Size([2, 1])
torch.Size([1, 2])
torch.Size([1, 1])
Features Shape torch.Size([1, 3])


In [23]:
h1 = activation(torch.mm(features,W1) + B1)
output = activation(torch.mm(h1,W2) + B2)

In [24]:
print(output)

tensor([[0.3171]])


In [25]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.47178738, 0.61774296, 0.552131  ],
       [0.17520863, 0.82166961, 0.86439255],
       [0.97759499, 0.64025898, 0.03348421],
       [0.04969728, 0.91049749, 0.07452388]])

In [26]:
b = torch.from_numpy(a)
b

tensor([[0.4718, 0.6177, 0.5521],
        [0.1752, 0.8217, 0.8644],
        [0.9776, 0.6403, 0.0335],
        [0.0497, 0.9105, 0.0745]], dtype=torch.float64)

In [27]:
b.numpy()

array([[0.47178738, 0.61774296, 0.552131  ],
       [0.17520863, 0.82166961, 0.86439255],
       [0.97759499, 0.64025898, 0.03348421],
       [0.04969728, 0.91049749, 0.07452388]])

In [28]:
b.mul_(2)

tensor([[0.9436, 1.2355, 1.1043],
        [0.3504, 1.6433, 1.7288],
        [1.9552, 1.2805, 0.0670],
        [0.0994, 1.8210, 0.1490]], dtype=torch.float64)

In [29]:
a

array([[0.94357475, 1.23548592, 1.10426201],
       [0.35041726, 1.64333921, 1.7287851 ],
       [1.95518998, 1.28051795, 0.06696843],
       [0.09939456, 1.82099498, 0.14904775]])